baseurl: ""
description: >-
  Assistant Professor at Seattle University. Historian of the modern Middle
  East with a special focus on women's rights
email: "novarobinson@seattleu.edu"
encoding: utf-8
exclude:
  - README.md
favicons:
  32: "/assets/logo.png"
lang: en-US
navigation_footer:
- title: Home
  url: /
- title: Publications
  url: /publications/
- title: Current Projects
  url: /current-projects/
- title: Teaching
  url: /teaching/
- title: About Me
  url: /about-me/
- title: Contact
  url: /contact-me/
navigation_header:
- title: Home
  url: /
- title: Publications
  url: /publications/
- title: Current Projects
  url: /current-projects/
- title: Teaching
  url: /teaching/
- title: About Me
  url: /about-me/
- title: Contact
  url: /contact-me/
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
remote_theme: jswanner/alembic
title: "Nova Robinson"
url: "https://www.novarobinson.com"
